services:
  - type: web
    name: ipo-tracker
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
